# Generated by Django 4.0.1 on 2022-03-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('type1', models.CharField(max_length=16)),
                ('type2', models.CharField(max_length=16, null=True)),
                ('height', models.CharField(max_length=8)),
                ('weight', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Pokemon',
                'ordering': ['number'],
            },
        ),
    ]
